// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG2N3FBQk1nnrx-oteDy_hKlK5pEnD65E',
    appId: '1:427528672554:web:0861f3769d7db0990b3a53',
    messagingSenderId: '427528672554',
    projectId: 'testingcli-35011',
    authDomain: 'testingcli-35011.firebaseapp.com',
    databaseURL: 'https://testingcli-35011-default-rtdb.firebaseio.com',
    storageBucket: 'testingcli-35011.appspot.com',
    measurementId: 'G-LDVDWFG8JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxEPLcf4jJpx7uhYEro8YC2GClTV8E9uY',
    appId: '1:427528672554:android:bc40424f173217a40b3a53',
    messagingSenderId: '427528672554',
    projectId: 'testingcli-35011',
    databaseURL: 'https://testingcli-35011-default-rtdb.firebaseio.com',
    storageBucket: 'testingcli-35011.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMFNrkhQ-uNyhcgm1IVD7GozcriDhsdHs',
    appId: '1:427528672554:ios:2e272ea3523e116b0b3a53',
    messagingSenderId: '427528672554',
    projectId: 'testingcli-35011',
    databaseURL: 'https://testingcli-35011-default-rtdb.firebaseio.com',
    storageBucket: 'testingcli-35011.appspot.com',
    iosBundleId: 'com.example.dsWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMFNrkhQ-uNyhcgm1IVD7GozcriDhsdHs',
    appId: '1:427528672554:ios:2e272ea3523e116b0b3a53',
    messagingSenderId: '427528672554',
    projectId: 'testingcli-35011',
    databaseURL: 'https://testingcli-35011-default-rtdb.firebaseio.com',
    storageBucket: 'testingcli-35011.appspot.com',
    iosBundleId: 'com.example.dsWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG2N3FBQk1nnrx-oteDy_hKlK5pEnD65E',
    appId: '1:427528672554:web:b9a6fc4c09ede3830b3a53',
    messagingSenderId: '427528672554',
    projectId: 'testingcli-35011',
    authDomain: 'testingcli-35011.firebaseapp.com',
    databaseURL: 'https://testingcli-35011-default-rtdb.firebaseio.com',
    storageBucket: 'testingcli-35011.appspot.com',
    measurementId: 'G-Q6QWYL5GHM',
  );

}